;;; ido-occasional-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ido-occasional.el

(autoload 'with-ido-completion "ido-occasional" "\
Wrap FUN in another interactive function with ido completion.

(fn FUN)" nil t)
(register-definition-prefixes "ido-occasional" '("ido-occasional-completing-read"))

;;; End of scraped data

(provide 'ido-occasional-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ido-occasional-autoloads.el ends here
